# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a421346155c91d35dd6387411f4f11c8a0b95e511137be7b395c2565fbd59212cefaa17b26d2ff70a287a6d93464a132d8ab520ce8c0ba5a8468dc5fb407fb83

test:
  secret_key_base: 536a0b1c9a801bd06a6f946aaa573bafaaeb406e87296aff3a1fc356939e2f3634d2a5e7a7924bbe69c44a6d02b8a212744c85c9e0a35caa7f401888dc63b76c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
